name: Manual Production Deployment

# This creates the manual "Run workflow" button in GitHub Actions
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'The package version tag to deploy (e.g., main-f1a2b3c4 or v1.0.0)'
        required: true
        type: string
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: destny69/package-modules/actions/deploy-artifact@v0.0.4
        with:
          package-name: 'frontend'
          version-tag: ${{ inputs.version-tag }} # Dynamically uses the UI input
          deploy-target-path: '/var/www/html/test'
          github-token: ${{ secrets.TOKEN }}
          server-ip: 188.245.106.180
          server-ssh-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          server-user: 'root'